<?php

include_once 'install-funcs.inc.php';

// set default timezone
date_default_timezone_set('UTC');

$OLD_PWD = $_SERVER['PWD'];

// work from lib directory
chdir(dirname($argv[0]));

if ($argv[0] === './pre-install.php' || $_SERVER['PWD'] !== $OLD_PWD) {
  // pwd doesn't resolve symlinks
  $LIB_DIR = $_SERVER['PWD'];
} else {
  // windows doesn't update $_SERVER['PWD']...
  $LIB_DIR = getcwd();
}

$APP_DIR = dirname($LIB_DIR);
$CONF_DIR = $APP_DIR . DIRECTORY_SEPARATOR . 'conf';
$CONFIG_FILE = $CONF_DIR . DIRECTORY_SEPARATOR . 'config.ini';
$APACHE_CONFIG_FILE = $CONF_DIR . DIRECTORY_SEPARATOR . 'httpd.conf';


// setup configuration defaults and help

$DEFAULTS = array(
  'APP_DIR' => $APP_DIR,
  'DATA_DIR' => str_replace('/apps/', '/data/', $APP_DIR),
  'MOUNT_PATH' => '/research/cpt',
  'DB_DSN' => 'sqlite:testdata.db',
  'DB_USER' => '',
  'DB_PASSWORD' => ''
);

$HELP_TEXT = array(
  'APP_DIR' => 'Absolute path to application root directory',
  'DATA_DIR' => 'Absolute path to application data directory',
  'MOUNT_PATH' => 'Url path to application',
  'DB_DSN' => 'Database connection DSN string',
  'DB_USER' => 'Read/write username for database connections',
  'DB_PASSWORD' => 'Password for database user'
);


include_once 'configure.php';


// output apache configuration
file_put_contents($APACHE_CONFIG_FILE, '
  # auto generated by ' . __FILE__ . ' at ' . date('r') . '
  Alias ' . $CONFIG['MOUNT_PATH'] . '/data ' . $CONFIG['DATA_DIR'] . '
  Alias ' . $CONFIG['MOUNT_PATH'] . ' ' . $CONFIG['APP_DIR'] . '/htdocs
  <Location ' . $CONFIG['MOUNT_PATH'] . '>
    Order Allow,Deny
    Allow from all
  </Location>

  RewriteEngine on

  RewriteRule ^' . $CONFIG['MOUNT_PATH'] . '/data/?(\w+)?/?(table|map)?/?$ ' .
      $CONFIG['MOUNT_PATH'] . '/data.php?region=$1&display=$2 [L,PT]
');
